# Generated by Django 2.1.3 on 2018-11-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ManyToManyField(blank=True, null=True, to='asignacion.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reglas',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='reglas.Vacuna'),
        ),
    ]
