# Generated by Django 2.1.3 on 2018-11-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('reglas', '0001_initial'),
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='numero_reglas',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='razones',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='reglas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reglas.Reglas'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios'),
        ),
    ]
