# Generated by Django 2.1.3 on 2018-11-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0002_auto_20181121_1502'),
        ('reglas', '0002_auto_20181121_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
