# Generated by Django 2.1.3 on 2018-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0003_delete_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='reglas',
            new_name='regla',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='personalizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
